name: Auto Release

on:
  push:
    branches: [ "master" ]
    paths: [ "setup.py" ]

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Release
        run: |
          VER=`cat setup.py | grep "plugin_version = " |sed 's/plugin_version = "//' |sed 's/"//'`
          DESCR=`git log $(git describe --tags --abbrev=0)..HEAD --pretty="format:%h | %s"`
          git tag $VER
          git push origin $VER
          gh release create $VER -t "v$VER" -n "$DESCR"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
